# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['event_id'], name='like_tab_event_i_60e563_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolemapping',
            index=models.Index(fields=['user_id'], name='user_role_t_user_id_825ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['id', 'channel'], name='event_tab_id_e6b524_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['event_id'], name='comment_tab_event_i_9c8d54_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['event_id'], name='participati_event_i_00929f_idx'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment_tab',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event_tab',
        ),
        migrations.AlterModelTable(
            name='like',
            table='like_tab',
        ),
        migrations.AlterModelTable(
            name='participation',
            table='participation_tab',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role_tab',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_tab',
        ),
        migrations.AlterModelTable(
            name='userrolemapping',
            table='user_role_tab',
        ),
    ]
